files:
  - source: /basics/*.md
    translation: /translations/%two_letters_code%/basics/*.md
  - source: /basics/assets/*.md
    translation: /translations/%two_letters_code%/basics/assets/*.md
  - source: /basics/how-retrieval-works/*.md
    translation: /translations/%two_letters_code%/basics/how-retrieval-works/*.md
  - source: /basics/how-storage-works/*.md
    translation: /translations/%two_letters_code%/basics/how-storage-works/*.md
  - source: /basics/project-and-community/*.md
    translation: /translations/%two_letters_code%/basics/project-and-community/*.md
  - source: /basics/the-blockchain/*.md
    translation: /translations/%two_letters_code%/basics/the-blockchain/*.md
  - source: /builder-cookbook/*md
    translation: /translations/%two_letters_code%/builder-cookbook/*.md
  - source: /builder-cookbook/dapps/*.md
    translation: /translations/%two_letters_code%/builder-cookbook/dapps/*.md
  - source: /builder-cookbook/data-storage/*.md
    translation: /translations/%two_letters_code%/builder-cookbook/data-storage/*.md
  - source: /networks/*.md
    translation: /translations/%two_letters_code%/networks/*.md
  - source: /networks/calibration/*.md
    translation: /translations/%two_letters_code%/networks/calibration/*.md
  - source: /networks/deprecated-networks/*.md
    translation: /translations/%two_letters_code%/networks/deprecated-networks/*.md
  - source: /networks/local-testnet/*.md
    translation: /translations/%two_letters_code%/networks/local-testnet/*.md
  - source: /networks/mainnet/*.md
    translation: /translations/%two_letters_code%/networks/mainnet/*.md
  - source: /nodes/*.md
    translation: /translations/%two_letters_code%/nodes/*.md
  - source: /nodes/full-nodes/*.md
    translation: /translations/%two_letters_code%/nodes/full-nodes/*.md
  - source: /nodes/implementations/*.md
    translation: /translations/%two_letters_code%/nodes/implementations/*.md
  - source: /nodes/lite-nodes/*.md
    translation: /translations/%two_letters_code%/nodes/lite-nodes/*.md
  - source: /reference/*.md
    translation: /translations/%two_letters_code%/reference/*.md
  - source: /reference/built-in-actors/*.md
    translation: /translations/%two_letters_code%/reference/built-in-actors/*.md
  - source: /reference/exchanges/*.md
    translation: /translations/%two_letters_code%/reference/exchanges/*.md
  - source: /reference/general/*.md
    translation: /translations/%two_letters_code%/reference/general/*.md
  - source: /reference/json-rpc/*.md
    translation: /translation/%two_letters_code%/reference/json-rpc/*.md
  - source: /smart-contracts/*.md
    translation: /translations/%two_letters_code%/smart-contracts/*.md
  - source: /smart-contracts/advanced/*.md
    translation: /translation/%two_letters_code%/smart-contracts/advanced/*.md
  - source: /smart-contracts/developing-contracts/*.md
    translation: /translations/%two_letters_code%/smart-contracts/developing-contracts/*.md
  - source: /smart-contracts/filecoin-evm-runtime/*.md
    translation: /translations/%two_letters_code%/smart-contracts/filecoin-evm-runtime/*.md
  - source: /smart-contracts/fundamentals/*.md
    translation: /translations/%two_letters_code%/smart-contracts/fundamentals/*.md
  - source: /smart-contracts/programmatic-storage/*.md
    translation: /translations/%two_letters_code%/smart-contracts/programmatic-storage/*.md
  - source: /storage-providers/*.md
    translation: /translations/%two_letters_code%/storage-providers/*.md
