files:
  - source: /basics/*.md
    translation: /basics/%locale_with_underscore%*.md
  - source: /basics/assets/*.md
    translation: /basics/assets/%locale_with_underscore%*.md
  - source: /basics/how-retrieval-works/*.md
    translation: /basics/how-retrieval-works/%locale_with_underscore%*.md
  - source: /basics/how-storage-works/*.md
    translation: /basics/how-storage-works/%locale_with_underscore%*.md
  - source: /basics/project-and-community/*.md
    translation: /basics/project-and-community/%locale_with_underscore%*.md
  - source: /basics/the-blockchain/*.md
    translation: /basics/the-blockchain/%locale_with_underscore%*.md
